version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "splash-page"
s3_bucket = "modamod-test-bucket"
s3_prefix = "splash-page"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
